batch_size: 8
layer1_units: 128
layer2_units: 64
pso_feature_weights:
- 0.6264464848745958
- 0.7290653029172027
- -0.1445681185562273
- -0.08508817594048745
- 0.5152339324841441
- 0.11005977296762615
- 0.9553237659599871
- 0.7752998165579347
- 0.8745628658906677
- 0.7034465816128839
- 0.0794818026158722
test_r2: 0.9697752077708857
test_rmse: 8.764135038213787
train_r2: 0.9284942764407738
train_rmse: 7.993717219182869
